// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyjllSbMueYCa9FdkpWn6ZJI3ClFFfAsg',
    appId: '1:976040961798:web:17d224455296ba82456087',
    messagingSenderId: '976040961798',
    projectId: 'talon-2e47e',
    authDomain: 'talon-2e47e.firebaseapp.com',
    storageBucket: 'talon-2e47e.firebasestorage.app',
    measurementId: 'G-H75V9KKM4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkKTfiz2vQsXB1HnUavnSZMeE2NCHCLJc',
    appId: '1:976040961798:android:e99b103a6b27fc34456087',
    messagingSenderId: '976040961798',
    projectId: 'talon-2e47e',
    storageBucket: 'talon-2e47e.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7VrxRGkQLSuBSVE9Y5VwuCSA0o1hZIeI',
    appId: '1:976040961798:ios:40c98b78a8b87d82456087',
    messagingSenderId: '976040961798',
    projectId: 'talon-2e47e',
    storageBucket: 'talon-2e47e.firebasestorage.app',
    iosBundleId: 'com.example.talon',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7VrxRGkQLSuBSVE9Y5VwuCSA0o1hZIeI',
    appId: '1:976040961798:ios:40c98b78a8b87d82456087',
    messagingSenderId: '976040961798',
    projectId: 'talon-2e47e',
    storageBucket: 'talon-2e47e.firebasestorage.app',
    iosBundleId: 'com.example.talon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyjllSbMueYCa9FdkpWn6ZJI3ClFFfAsg',
    appId: '1:976040961798:web:ee79d958479bd042456087',
    messagingSenderId: '976040961798',
    projectId: 'talon-2e47e',
    authDomain: 'talon-2e47e.firebaseapp.com',
    storageBucket: 'talon-2e47e.firebasestorage.app',
    measurementId: 'G-7Y9RN9R1PJ',
  );
}
